package projectaurora.world.layer;

import net.minecraft.world.gen.layer.GenLayer;
import net.minecraft.world.World;

public abstract class BaseGenLayer extends GenLayer {
	
	protected BaseGenLayer baseParent;

	public BaseGenLayer(long seed) {
		super(seed);
	}
	
	@Override
	public void initWorldGenSeed(long seed) {
		super.initWorldGenSeed(seed);
		
		if(this.baseParent != null) {
			this.baseParent.initWorldGenSeed(seed);
		}
	}
	
    /**
     * Use {@link #getInts(World, int, int, int, int)} instead. Will throw RuntimeException.
     */
	@Override
	public final int[] getInts(int x, int z, int xSize, int zSize) {
		throw new RuntimeException("getInts called for Aurora. Use the world sensitive version instead.");
	}

    /**
     * Returns a list of integer values generated by this layer. These may be interpreted as temperatures, rainfall
     * amounts, or biomeList[] indices based on the particular GenLayer subclass. Custom world version.
     */
	public abstract int[] getInts(World world, int x, int z, int xSize, int zSize);
}